@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "Sequencing\npipeline" as seqpipe
control "seq_to_irods_archiver" as archiver
control "npg_publish_illumina_run.pl" as publish_illumina_run
participant "Staging\nvolume" as staging
participant "Sample\nsheet" as samplesheet
boundary "Perl ML\nWarehouse\nAPI" as perl_mlwh_api
database "ML\nWarehouse" as mlwh
boundary "NPG business\nAPI" as npg_business_api
boundary "Perl iRODS\nAPI" as perl_irods_api
boundary "baton" as baton
participant "iRODS" as irods

activate mlwh #lightgreen
activate irods #dimgray
activate staging #goldenrod
activate seqpipe

seqpipe -> archiver
activate archiver
archiver -> publish_illumina_run
activate publish_illumina_run
activate baton

publish_illumina_run -> perl_irods_api

loop data files

group Copy data
npg_business_api -> perl_irods_api
perl_irods_api -> baton
baton -> staging
staging --> baton : Data files
baton -> irods : iRODS\nC API
irods --> baton
baton --> perl_irods_api

npg_business_api --> npg_business_api : Build metadata

npg_business_api -> perl_irods_api : Set \nmetadata
perl_irods_api -> baton
baton -> irods : iRODS\nC API
irods --> baton
baton --> perl_irods_api
perl_irods_api --> npg_business_api
end

group Add primary metadata
npg_business_api -> staging
staging --> npg_business_api : Composition JSON file
npg_business_api --> npg_business_api : Build\nmetadata

npg_business_api -> perl_irods_api : Set\nmetadata
perl_irods_api -> baton
baton -> irods : iRODS\nC API
irods --> baton
baton --> perl_irods_api
perl_irods_api --> npg_business_api
end group

group Add secondary metadata
npg_business_api -> staging
staging --> npg_business_api : Composition JSON file

alt Using samplesheet
    npg_business_api -> samplesheet : Metadata\nrequest
    samplesheet -> staging
    staging--> npg_business_api : Samplesheet file
else Using ML warehouse
    npg_business_api -> perl_mlwh_api : Metadata\nrequest
    perl_mlwh_api -> mlwh : SQL\nquery
    mlwh --> perl_mlwh_api
    perl_mlwh_api --> npg_business_api
end

npg_business_api --> npg_business_api : Build\nmetadata

npg_business_api -> perl_irods_api : Compare/update\nmetadata
perl_irods_api -> baton
baton -> irods : iRODS\nC API
irods --> baton
baton --> perl_irods_api
perl_irods_api --> npg_business_api
end group

group Update permissions
npg_business_api -> npg_business_api : Metadata\nrequest
perl_irods_api -> baton
baton -> irods : iRODS\nC API
irods --> baton
baton --> perl_irods_api
perl_irods_api --> npg_business_api

npg_business_api --> npg_business_api : Build\npermissions

npg_business_api -> perl_irods_api : Compare/update\npermissions
perl_irods_api -> baton
baton -> irods : iRODS\nC API
irods --> baton
baton --> perl_irods_api
perl_irods_api --> npg_business_api
end group

perl_irods_api --> publish_illumina_run
end

destroy baton
destroy publish_illumina_run
destroy archiver
deactivate seqpipe

@enduml
